/* eslint-disable */
// Generated by scripts/build-client-spec.mjs — do not edit by hand.
(function (global) {
  const SPEC = {
  "phases": {
    "version": 1,
    "handPhases": [
      {
        "id": "waiting",
        "label": "等待开始",
        "inHand": false,
        "gates": {
          "canStart": true,
          "canConfigureRoom": true,
          "canAct": false
        }
      },
      {
        "id": "preflop",
        "label": "翻牌前",
        "inHand": true,
        "gates": {
          "canStart": false,
          "canConfigureRoom": false,
          "canAct": true
        }
      },
      {
        "id": "flop",
        "label": "翻牌",
        "inHand": true,
        "gates": {
          "canStart": false,
          "canConfigureRoom": false,
          "canAct": true
        }
      },
      {
        "id": "turn",
        "label": "转牌",
        "inHand": true,
        "gates": {
          "canStart": false,
          "canConfigureRoom": false,
          "canAct": true
        }
      },
      {
        "id": "river",
        "label": "河牌",
        "inHand": true,
        "gates": {
          "canStart": false,
          "canConfigureRoom": false,
          "canAct": true
        }
      },
      {
        "id": "showdown",
        "label": "摊牌",
        "inHand": false,
        "gates": {
          "canStart": false,
          "canConfigureRoom": true,
          "canAct": false
        },
        "notes": "showdownPending：底池尚未结算，RoomManager 定时 finalizeShowdown"
      },
      {
        "id": "ended",
        "label": "局结束",
        "inHand": false,
        "gates": {
          "canStart": true,
          "canConfigureRoom": true,
          "canAct": false
        }
      }
    ],
    "roomContexts": [
      {
        "id": "no_engine",
        "label": "房间大厅",
        "handNull": true,
        "description": "engine 未创建；客户端 handPhase 伪值为 lobby"
      },
      {
        "id": "engine_waiting",
        "handPhase": "waiting",
        "description": "引擎初始态；生产环境少见，startHand 后直接进入 preflop"
      },
      {
        "id": "engine_ended",
        "handPhase": "ended",
        "description": "局间；可开始新一局"
      }
    ],
    "transitions": [
      {
        "from": "no_engine",
        "event": "game:start",
        "to": "preflop"
      },
      {
        "from": "waiting",
        "event": "startHand",
        "to": "preflop"
      },
      {
        "from": "preflop",
        "event": "roundComplete",
        "to": "flop"
      },
      {
        "from": "flop",
        "event": "roundComplete",
        "to": "turn"
      },
      {
        "from": "turn",
        "event": "roundComplete",
        "to": "river"
      },
      {
        "from": "river",
        "event": "roundComplete",
        "to": "showdown"
      },
      {
        "from": "preflop",
        "event": "foldWin",
        "to": "ended"
      },
      {
        "from": "flop",
        "event": "foldWin",
        "to": "ended"
      },
      {
        "from": "turn",
        "event": "foldWin",
        "to": "ended"
      },
      {
        "from": "river",
        "event": "foldWin",
        "to": "ended"
      },
      {
        "from": "showdown",
        "event": "finalizeShowdown",
        "to": "ended"
      },
      {
        "from": "ended",
        "event": "game:start",
        "to": "preflop"
      }
    ]
  },
  "uiModes": {
    "version": 1,
    "screens": [
      "entry",
      "room"
    ],
    "settingsModes": [
      "edit",
      "locked",
      "readonly"
    ],
    "modes": [
      {
        "id": "entry",
        "screen": "entry",
        "label": "进入牌桌前",
        "flags": {
          "showRoomPanel": false,
          "showLobbyCard": true,
          "showActionBar": false,
          "showStartButton": false,
          "showResultPanel": false,
          "showTableSeatsAsLobby": false
        }
      },
      {
        "id": "room_lobby",
        "screen": "room",
        "label": "房间大厅",
        "match": {
          "handNull": true
        },
        "flags": {
          "showRoomPanel": true,
          "showLobbyCard": false,
          "showActionBar": false,
          "showStartButton": true,
          "showResultPanel": false,
          "showTableSeatsAsLobby": true,
          "phaseLabel": "大厅"
        }
      },
      {
        "id": "room_in_hand",
        "screen": "room",
        "label": "局内",
        "match": {
          "inHand": true
        },
        "flags": {
          "showRoomPanel": true,
          "showLobbyCard": false,
          "showActionBar": true,
          "showStartButton": false,
          "showResultPanel": false,
          "showTableSeatsAsLobby": false
        }
      },
      {
        "id": "room_showdown",
        "screen": "room",
        "label": "摊牌亮牌",
        "match": {
          "handPhase": "showdown"
        },
        "flags": {
          "showRoomPanel": true,
          "showLobbyCard": false,
          "showActionBar": false,
          "showStartButton": false,
          "showResultPanel": false,
          "showTableSeatsAsLobby": false,
          "revealHoleCards": true
        }
      },
      {
        "id": "room_ended",
        "screen": "room",
        "label": "局结束",
        "match": {
          "handPhase": "ended"
        },
        "flags": {
          "showRoomPanel": true,
          "showLobbyCard": false,
          "showActionBar": false,
          "showStartButton": true,
          "showResultPanel": true,
          "showTableSeatsAsLobby": false,
          "delayResultPanelMs": 3000
        }
      }
    ]
  },
  "socketEvents": {
    "version": 1,
    "events": [
      {
        "direction": "C→S",
        "name": "room:create",
        "payload": {
          "playerName": "string"
        },
        "ack": {
          "ok": true,
          "session": "object",
          "gameState": "GameState"
        }
      },
      {
        "direction": "C→S",
        "name": "room:join",
        "payload": {
          "roomId": "string",
          "playerName": "string"
        },
        "ack": {
          "ok": true,
          "session": "object",
          "gameState": "GameState"
        }
      },
      {
        "direction": "C→S",
        "name": "room:resume",
        "payload": {
          "roomId": "string",
          "playerId": "string",
          "token": "string"
        },
        "ackOk": {
          "ok": true,
          "session": "object",
          "gameState": "GameState"
        },
        "ackErrorCodes": [
          "ROOM_NOT_FOUND",
          "SESSION_INVALID",
          "PLAYER_NOT_FOUND"
        ]
      },
      {
        "direction": "C→S",
        "name": "room:leave",
        "payload": {},
        "ack": {
          "ok": true
        }
      },
      {
        "direction": "C→S",
        "name": "room:settings",
        "payload": {
          "startingChips?": "number",
          "smallBlind?": "number",
          "bigBlind?": "number"
        },
        "ack": {
          "ok": true,
          "settings?": "RoomSettings",
          "gameState?": "GameState"
        }
      },
      {
        "direction": "C→S",
        "name": "game:start",
        "payload": {},
        "ack": {
          "ok": true,
          "gameState?": "GameState"
        }
      },
      {
        "direction": "C→S",
        "name": "game:action",
        "payload": {
          "action": "fold|check|call|bet|raise|allin",
          "amount?": "number"
        },
        "ack": {
          "ok": true
        }
      },
      {
        "direction": "S→C",
        "name": "gameState",
        "payload": "GameState"
      }
    ]
  },
  "timing": {
    "version": 1,
    "constants": {
      "SHOWDOWN_PAUSE_MS": {
        "default": 1800,
        "env": "SHOWDOWN_PAUSE_MS",
        "owner": "server",
        "description": "摊牌亮牌停留后再 finalizeShowdown"
      },
      "RESULT_PANEL_DELAY_MS": {
        "default": 3000,
        "owner": "client",
        "description": "ended 阶段延迟展开结果面板"
      },
      "ACTION_TIMEOUT_MS": {
        "default": 30000,
        "env": "ACTION_TIMEOUT_MS",
        "owner": "server"
      },
      "OFFLINE_AUTO_FOLD_MS": {
        "default": 30000,
        "env": "OFFLINE_AUTO_FOLD_MS",
        "owner": "server"
      }
    }
  }
};

  const IN_HAND_PHASES = new Set(['preflop', 'flop', 'turn', 'river']);

function buildPhaseIndex(phasesSpec) {
  const byId = new Map();
  for (const phase of phasesSpec?.handPhases || []) {
    byId.set(phase.id, phase);
  }
  return byId;
}

function getHandPhaseIds(phasesSpec) {
  return (phasesSpec?.handPhases || []).map((phase) => phase.id);
}

function getPhaseLabel(phasesSpec, phaseId) {
  const phase = buildPhaseIndex(phasesSpec).get(phaseId);
  return phase?.label || phaseId || '—';
}

function isInHandPhase(handPhase) {
  return IN_HAND_PHASES.has(handPhase);
}

function getSettingsHandPhase(hand) {
  return hand?.phase ?? 'lobby';
}

function isSettingsEditable(gameState, hand) {
  if (!gameState) return false;
  if (gameState.canEditSettings) return true;
  if (!hand) return true;
  const phase = hand.phase;
  return phase === 'waiting' || phase === 'ended' || phase === 'showdown';
}

function resolveSettingsMode(gameState, hand, viewerPlayerId) {
  if (!gameState?.hostPlayerId) return 'readonly';
  if (!viewerPlayerId || gameState.hostPlayerId !== viewerPlayerId) return 'readonly';
  if (isSettingsEditable(gameState, hand)) return 'edit';
  return 'locked';
}

function resolveUiMode(gameState, options = {}) {
  const screen = options.screen || 'room';
  const phasesSpec = options.phasesSpec;
  const uiModesSpec = options.uiModesSpec;

  if (screen === 'entry') {
    const entryMode = (uiModesSpec?.modes || []).find((mode) => mode.id === 'entry');
    return {
      mode: 'entry',
      screen: 'entry',
      handNull: true,
      handPhase: 'lobby',
      inHand: false,
      isShowdown: false,
      isEnded: false,
      isSpectating: false,
      settingsMode: 'readonly',
      phaseLabel: entryMode?.label || '进入牌桌前',
      flags: { ...(entryMode?.flags || {}) },
    };
  }

  const hand = gameState?.hand ?? null;
  const viewer = gameState?.viewer ?? null;
  const handPhase = hand?.phase ?? null;
  const handNull = hand === null;
  const inHand = Boolean(hand && isInHandPhase(handPhase));
  const isShowdown = handPhase === 'showdown';
  const isEnded = handPhase === 'ended';
  const isSpectating = Boolean(viewer?.isSpectating);

  let modeId = 'room_lobby';
  if (handNull || handPhase === 'waiting') modeId = 'room_lobby';
  else if (inHand) modeId = 'room_in_hand';
  else if (isShowdown) modeId = 'room_showdown';
  else if (isEnded) modeId = 'room_ended';

  const modeDef = (uiModesSpec?.modes || []).find((mode) => mode.id === modeId);
  const settingsHandPhase = getSettingsHandPhase(hand);
  const settingsMode = resolveSettingsMode(gameState, hand, options.viewerPlayerId);

  let phaseLabel = modeDef?.flags?.phaseLabel;
  if (!phaseLabel && handPhase) phaseLabel = getPhaseLabel(phasesSpec, handPhase);
  if (!phaseLabel) phaseLabel = modeDef?.flags?.phaseLabel || modeDef?.label || '大厅';

  return {
    mode: modeId,
    screen: 'room',
    handNull,
    handPhase: settingsHandPhase,
    serverHandPhase: handPhase,
    inHand,
    isShowdown,
    isEnded,
    isSpectating,
    settingsMode,
    phaseLabel,
    flags: { ...(modeDef?.flags || {}) },
  };
}

{ IN_HAND_PHASES };


  const PHASE_LABEL = Object.fromEntries(
    (SPEC.phases.handPhases || []).map((phase) => [phase.id, phase.label]),
  );

  global.TexasHoldemSpec = {
    SPEC,
    PHASE_LABEL,
    IN_HAND_PHASES,
    RESULT_PANEL_DELAY_MS: SPEC.timing.constants.RESULT_PANEL_DELAY_MS.default,
    SETTINGS_MODE: { EDIT: 'edit', LOCKED: 'locked', READONLY: 'readonly' },
    getHandPhaseIds: () => (SPEC.phases.handPhases || []).map((phase) => phase.id),
    getPhaseLabel: (phaseId) => getPhaseLabel(SPEC.phases, phaseId),
    isInHandPhase,
    getSettingsHandPhase,
    isSettingsEditable,
    resolveSettingsMode: (gameState, hand, options = {}) => resolveSettingsMode(
      { ...gameState, _viewerPlayerId: options.viewerPlayerId, _isHost: options.isHost },
      hand,
    ),
    resolveUiMode: (gameState, options = {}) => resolveUiMode(gameState, {
      ...options,
      phasesSpec: SPEC.phases,
      uiModesSpec: SPEC.uiModes,
    }),
  };
})(typeof window !== 'undefined' ? window : globalThis);
